<script setup lang="ts">
import { legalEnglish } from "~/shared/legal-en"
const { t, localePath, locale, basePath } = useLocale()

useSeoMeta({title:() => t('Tentang Kami | Sudut Haramain'),description:() => t('Mengenal Sudut Haramain, media digital yang menghadirkan informasi, cerita, berbagai sisi kehidupan, dan panduan praktis dari Makkah dan Madinah.')})
const sections=[{id:'apa-itu',title:'Lebih dari sekadar tempat mencari informasi.',paragraphs:['Sudut Haramain hadir untuk membantu masyarakat Indonesia mengenal Makkah dan Madinah lebih dekat.','Bukan hanya tentang perjalanan menuju dua kota suci, tetapi juga tentang kehidupan di dalamnya: bagaimana berpindah dari satu tempat ke tempat lain, memahami lingkungan sekitar, mengenal kultur lokal, menemukan kebutuhan sehari-hari, hingga memperoleh informasi yang relevan selama berada di Haramain.','Kami ingin informasi tentang Makkah dan Madinah terasa lebih dekat, lebih mudah dipahami, dan benar-benar berguna ketika dibutuhkan.']},{id:'mengapa',title:'Mengapa Sudut Haramain hadir?',paragraphs:['Informasi mengenai Makkah dan Madinah tersebar di banyak tempat. Sebagian cepat berubah, sebagian sulit ditemukan, dan sebagian lainnya baru terasa penting ketika seseorang sudah berada di lapangan.','Sudut Haramain mencoba mengumpulkan berbagai informasi tersebut dari satu sudut yang lebih praktis dan mudah dijelajahi.','Tujuannya sederhana: membantu pembaca memahami Haramain dengan lebih baik sebelum berangkat, ketika berada di sana, maupun setelah kembali.']},{id:'yang-ditemukan',title:'Yang dapat Anda temukan di Sudut Haramain',paragraphs:['Kehidupan dan kultur, informasi Makkah dan Madinah, perjalanan, ibadah, cerita dan sorotan dari Haramain, serta panduan praktis.']},{id:'prinsip',title:'Informasi yang dekat dengan kebutuhan nyata.',paragraphs:['Kami berusaha menyajikan informasi dengan bahasa yang mudah dipahami, konteks yang jelas, dan kegunaan yang nyata bagi pembaca.','Kami juga menyadari bahwa kondisi di Makkah dan Madinah dapat berubah. Jadwal, aturan, akses lokasi, transportasi, harga, maupun kebijakan setempat dapat mengalami pembaruan dari waktu ke waktu. Karena itu, pembaca tetap dianjurkan untuk memperhatikan informasi resmi dan kondisi terbaru ketika mengambil keputusan di lapangan.']},{id:'ekosistem',title:'Ekosistem Sudut Haramain',paragraphs:['Sudut Haramain berkembang sebagai ekosistem yang berangkat dari kebutuhan masyarakat Indonesia terhadap Haramain.','Sudut Haramain — Media digital dan informasi praktis Makkah–Madinah.','Sudut Haramain Tour — Layanan Umroh Mandiri dan Land Arrangement.']},{id:'penutup',title:'Melihat Makkah dan Madinah lebih dekat, lewat informasi, cerita, dan panduan yang benar-benar berguna.',paragraphs:['Selamat menjelajahi Sudut Haramain.']}]

const localizedSections = computed(() => locale.value === 'en' ? legalEnglish.about : sections)
</script><template><LegalPageShell :eyebrow="t('TENTANG SUDUT HARAMAIN')" :title="t('Melihat Haramain dari Sudut yang Lebih Dekat.')" :intro="t('Sudut Haramain adalah media digital yang menghadirkan informasi, cerita, berbagai sisi kehidupan, dan panduan praktis dari Makkah dan Madinah.')" updated="" :sections="localizedSections" kind="about"/></template>
